import type { Metadata } from "next";
import localFont from "next/font/local";
import "../../../globals.css";
import Navbar from "@/components/Navbar";
import Sidebar from "@/components/Sidebar";

const geistSans = localFont({
  src: "../../../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../../../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="fixed top-0 left-0 right-0 z-10">  
          <Navbar />
        </div>
        <div className="flex">
          <div className="fixed top-16 h-full"> 
            <Sidebar />
          </div>
          <div className="ml-80 mt-40 overflow-y-auto">  
            {children}
          </div>
        </div>
       
      </body>
    </html>
  );
}
